{
 "title": "Loki - prtomtail logs",
 "description": "Universal and flexible dashboard for logging",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values({host=~\".+\"}, host)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values({host=\"$host\"}, job)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\",  job=~\"$job\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\",  job=~\"$job\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{host=\"$host\", job=~\"$job\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\", job=~\"$job\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\"",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\", job=~\"$job\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (job)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\",  job=~\"$job\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({host=\"$host\",  job=~\"$job\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\", job=~\"$job\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (job)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({host=\"$host\",  job=~\"$job\"} |~ \"(?i)$searchable_pattern\")[30s])) by (job)"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\", job=~\"$job\"})[$__interval])) by (stream)"
    }
   ]
  }
 ]
}