---
- name: Ensure loki conf folder
  file:
    path: "{{ loki_conf_path }}"
    state: directory

- name: Push loki conf template
  template:
    src: "{{ loki_conf_template }}"
    dest: "{{ loki_conf_path }}/local-config.yaml"

- name: Start loki containter
  docker_container:
    name: loki
    image: "grafana/loki:{{ loki_container_tag }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ loki_conf_path }}/local-config.yaml:/etc/loki/local-config.yaml"
    ports:
     - "{{ loki_exposed_port }}:{{ loki_container_port }}"
