---
- name: 'promtail | get latest release from GitHub'
  shell: curl --silent "https://api.github.com/repos/grafana/loki/releases/latest" | jq -r .tag_name | sed "s/v//"
  args:
    warn: false
  register: promtail_latest_version
  run_once: true

- name: 'promtail | download'
  get_url:
    url: https://github.com/grafana/loki/releases/download/v{{ promtail_version|default(promtail_latest_version.stdout) }}/promtail-linux-amd64.zip
    dest: /tmp

- name: 'promtail | unarchive'
  unarchive:
    remote_src: yes
    src: /tmp/promtail-linux-amd64.zip
    dest: /tmp

- name: 'promtail | Ensure basedir exists'
  file:
    state: directory
    path: /opt/promtail

- name: 'promtail | push configuration file'
  template:
    src: conf/promtail-local-config.yaml
    dest: /opt/promtail/promtail-local-config.yaml
    owner: root
    group: root
    mode: 0600

- name: 'promtail | install unit file to systemd'
  template:
    src: systemd/promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: 0600

- name: 'promtail | configure systemd to use service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: promtail.service

- name: 'promtail | move to /opt/promtail'
  copy:
    src: /tmp/promtail-linux-amd64
    dest: /opt/promtail/promtail-linux-amd64
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  notify:
    - 'promtail | restart service'
