---
- name: 'promtail | update APT Cache'
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: ['promtail']

- name: 'promtail | pre-requirements install'
  apt:
    name:
      - curl
      - jq
    state: present
  tags: ['promtail']
