---
- name: 'Loki | server | restart container'
  docker_container:
    name: loki
    restart: yes
  tags: ['loki']

- name: 'promtail | restart service'
  systemd:
    name: promtail.service
    state: restarted
    enabled: yes
  tags: ['promtail']
